### ISSUE TITLE
ZFS on Linux crash - appears related to this BFS fork.

### ISSUE THREAD

**Issue by sempervictus** [cchalpha/linux-gc#1]
While building up the next set of test components for our internal systems, we keep running into a strange issue with ZFS where crashes occur consistently, but at random times during boot or early operation. The stack trace appears to indicate that an operation was rescheduled with resched_closest_idle and the workload performs direct memory operations (kmem_alloc). I'm not a kernel developer, so running a bit blind here, but i'm wondering if you've seen anything like this in other situations, or if this exposes an edge case of some sort in BFS itself?

The original ZFS on Linux issue is here: https://github.com/zfsonlinux/zfs/issues/3608, and an image of the stack trace is here: http://ibin.co/299z5d7YF0jJ. Any light you could shed on where to look would be greatly appreciated. Thank you

**Comment by kernelOfTruth** [comment]
http://ck-hack.blogspot.com/2011/11/31-ck1-bfs-0414.html?showComment=1320402676271#c8901418101455539444

hm, that's an rather old kernel :/

and it seems that issue was fixed with the next release:

http://ck-hack.blogspot.co.at/search?updated-max=2012-01-05T20:37:00%2B11:00&max-results=4&start=48&by-date=false

http://ck-hack.blogspot.co.at/2011/11/310-ck2-bfs-0415.html

unfortunately exactly the folder for 3.1.0 kernel is missing at Con's server so it might be rather hard to see what those listed patches changed ...

**Comment by sempervictus** [comment]
The problem description sounds eerily similar to discussions in ZoL about direct memory ops, i'm thinking that BFS somehow derails SPL's dangerous behavior protections which were supposed to be otherwise bounded by scheduling mechanisms (buckshot-grade theory, need to dig deeper).

**Comment by cchalpha** [comment]
Close this old issue. Please reopen if it is still on recent kernel release.
